# 503x346x288 (50122944)
mesh:
- direction: x
  start: -15.0
  subDomains:
  - cells: 22
    end: -2.0
    stretchRatio: 0.8333333333
  - cells: 9
    end: -1.55
    stretchRatio: 1.0
  - cells: 18
    end: -1.1
    stretchRatio: 0.9090909091
  - cells: 330
    end: 2.2
    stretchRatio: 1.0
  - cells: 56
    end: 3.6
    stretchRatio: 1.03
  - cells: 48
    end: 6.0
    stretchRatio: 1.0
  - cells: 20
    end: 15.0
    stretchRatio: 1.2
- direction: y
  start: -12.5
  subDomains:
  - cells: 20
    end: -3.0
    stretchRatio: 0.8333333333
  - cells: 30
    end: -1.5
    stretchRatio: 1.0
  - cells: 18
    end: -1.05
    stretchRatio: 0.9090909091
  - cells: 210
    end: 1.05
    stretchRatio: 1.0
  - cells: 18
    end: 1.5
    stretchRatio: 1.1
  - cells: 30
    end: 3.0
    stretchRatio: 1.0
  - cells: 20
    end: 12.5
    stretchRatio: 1.2
- direction: z
  start: -12.5
  subDomains:
  - cells: 21
    end: -1.0
    stretchRatio: 0.8333333333
  - cells: 1
    end: -0.95
    stretchRatio: 1.0
  - cells: 17
    end: -0.55
    stretchRatio: 0.9090909091
  - cells: 210
    end: 1.55
    stretchRatio: 1.0
  - cells: 17
    end: 1.95
    stretchRatio: 1.1
  - cells: 1
    end: 2.0
    stretchRatio: 1.0
  - cells: 21
    end: 12.5
    stretchRatio: 1.2

flow:
  nu: 0.005
  initialVelocity: [1.0, 0.0, 0.0]
  boundaryConditions:
  - location: xMinus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
    w: [DIRICHLET, 0.0]
  - location: xPlus
    u: [CONVECTIVE, 1.0]
    v: [CONVECTIVE, 1.0]
    w: [CONVECTIVE, 1.0]
  - location: yMinus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
    w: [DIRICHLET, 0.0]
  - location: yPlus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
    w: [DIRICHLET, 0.0]
  - location: zMinus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
    w: [DIRICHLET, 0.0]
  - location: zPlus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
    w: [DIRICHLET, 0.0]

parameters:
  dt: 0.0013056664155607794
  startStep: 0
  nt: 5000
  nsave: 250
  nrestart: 5000
  convection: ADAMS_BASHFORTH_2
  diffusion: CRANK_NICOLSON
  velocitySolver:
    type: CPU
    config: config/velocity_solver.info
  poissonSolver:
    type: GPU
    config: config/poisson_solver.info
  forcesSolver:
    type: CPU
    config: config/forces_solver.info

bodies:
- type: points
  name: wing
  file: wing.body
  kinematics:
    c: 1.0
    AR: 1.27
    CoR: [0.0, 0.0, 0.0]
    f: 0.7658924117846005
    A_phi: 0.7853981633974483
    A_theta: 0.7853981633974483
    psi: 1.5707963267948966
    theta_bias: 0.0
